services:
    odiseo_sylius_mailchimp_plugin.command.sync_stores:
        class: Odiseo\SyliusMailchimpPlugin\Command\SyncStoresCommand
        arguments:
            - "@sylius.repository.channel"
            - "@odiseo_sylius_mailchimp_plugin.handler.store_register"
        tags:
            - { name: "console.command", command: "odiseo:mailchimp:sync-stores" }

    odiseo_sylius_mailchimp_plugin.add_customers.command:
        class: Odiseo\SyliusMailchimpPlugin\Command\AddCustomersCommand
        arguments:
            - "@odiseo.mailchimp_plugin.ecommerce.api"
            - "@sylius.context.channel"
            - "@sylius.repository.customer"

    odiseo_sylius_mailchimp_plugin.command.sync_products:
        class: Odiseo\SyliusMailchimpPlugin\Command\SyncProductsCommand
        arguments:
            - "@sylius.repository.product"
            - "@odiseo_sylius_mailchimp_plugin.handler.product_register"
        tags:
            - { name: "console.command", command: "odiseo:mailchimp:sync-products" }