services:
    odiseo_sylius_mailchimp_plugin.handler.store_register:
        class: Odiseo\SyliusMailchimpPlugin\Handler\StoreRegisterHandler
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.ecommerce.api"
            - "@odiseo_sylius_mailchimp_plugin.default.list_id_provider"

    odiseo_sylius_mailchimp_plugin.handler.product_register:
        class: Odiseo\SyliusMailchimpPlugin\Handler\ProductRegisterHandler
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.ecommerce.api"
            - "@router"
            - "@liip_imagine.cache.manager"

    odiseo_sylius_mailchimp_plugin.handler.customer_register:
        class: Odiseo\SyliusMailchimpPlugin\Handler\CustomerRegisterHandler
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.ecommerce.api"

    odiseo_sylius_mailchimp_plugin.handler.cart_register:
        class: Odiseo\SyliusMailchimpPlugin\Handler\CartRegisterHandler
        public: true
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.ecommerce.api"
            - "@router"

    odiseo_sylius_mailchimp_plugin.handler.order_register:
        class: Odiseo\SyliusMailchimpPlugin\Handler\OrderRegisterHandler
        public: true
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.ecommerce.api"

    odiseo_sylius_mailchimp_plugin.handler.customer_newsletter_subscription:
        class: Odiseo\SyliusMailchimpPlugin\Handler\CustomerNewsletterSubscriptionHandler
        arguments:
            - "@sylius.repository.customer"
            - "@sylius.factory.customer"
            - "@sylius.manager.customer"
            - "@odiseo_sylius_mailchimp_plugin.lists.api"
            - "%env(ODISEO_MAILCHIMP_DEFAULT_LISTID)%"