services:
    odiseo_sylius_mailchimp_plugin.provider.default_list_id_provider:
        class: Odiseo\SyliusMailchimpPlugin\Provider\DefaultListIdProvider
        public: true
        arguments:
            - '%env(ODISEO_MAILCHIMP_DEFAULT_LISTID)%'
