winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                register_cart:
                    on: ["address"]
                    do: ["@odiseo_sylius_mailchimp_plugin.handler.cart_register", "register"]
                    args: ["object"]
                    priority: 3
                register_order:
                    on: ["complete"]
                    do: ["@odiseo_sylius_mailchimp_plugin.handler.order_register", "register"]
                    args: ["object"]
                    priority: 3
