winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                register_cart:
                    on: ["address"]
                    do: ["@odiseo_sylius_mailchimp_plugin.handler.cart_register", "register"]
                    args: ["object"]
                    priority: 3
    sylius_order_payment:
        callbacks:
            after:
                register_order:
                    on: ["pay"]
                    do: ["@odiseo_sylius_mailchimp_plugin.handler.order_register", "register"]
                    args: ["object"]
                    priority: 3

monolog:
    channels: ['mailchimp']
    handlers:
        mailchimp:
            type: stream
            path: "%kernel.logs_dir%/mailchimp_%kernel.environment%.log"
            level: info
            channels: [mailchimp]
