parameters:
    odiseo.mailchimp_plugin.listener.ecommerce_cart.class: Odiseo\SyliusMailchimpPlugin\EventListener\MailchimpEcommerceCartListener
    odiseo.mailchimp_plugin.listener.ecommerce_order.class: Odiseo\SyliusMailchimpPlugin\EventListener\MailchimpEcommerceOrderListener
    odiseo.mailchimp_plugin.subscriber.customer_newsletter.class: Odiseo\SyliusMailchimpPlugin\EventListener\CustomerNewsletterSubscriber
    odiseo.mailchimp_plugin.subscriber.ecommerce_store.class: Odiseo\SyliusMailchimpPlugin\EventListener\MailchimpEcommerceStoreSubscriber
    odiseo.mailchimp_plugin.subscriber.ecommerce_customer.class: Odiseo\SyliusMailchimpPlugin\EventListener\MailchimpEcommerceCustomerSubscriber
    odiseo.mailchimp_plugin.subscriber.ecommerce_product.class: Odiseo\SyliusMailchimpPlugin\EventListener\MailchimpEcommerceProductSubscriber

services:
    odiseo.mailchimp_plugin.listener.ecommerce_cart:
        class: "%odiseo.mailchimp_plugin.listener.ecommerce_cart.class%"
        public: true
        arguments:  ["@odiseo.mailchimp_plugin.mailchimp", "@sylius.context.channel", "@router"]

    odiseo.mailchimp_plugin.listener.ecommerce_order:
        class: "%odiseo.mailchimp_plugin.listener.ecommerce_order.class%"
        public: true
        arguments:  ["@odiseo.mailchimp_plugin.mailchimp", "@sylius.context.channel"]

    odiseo.mailchimp_plugin.subscriber.customer_newsletter:
        class: "%odiseo.mailchimp_plugin.subscriber.customer_newsletter.class%"
        arguments: ["@odiseo.mailchimp_plugin.mailchimp"]
        tags:
             - { name: doctrine.event_subscriber }

    odiseo.mailchimp_plugin.subscriber.ecommerce_store:
        class: "%odiseo.mailchimp_plugin.subscriber.ecommerce_store.class%"
        arguments:  ["@odiseo.mailchimp_plugin.mailchimp"]
        tags:
            - { name: doctrine.event_subscriber }

    odiseo.mailchimp_plugin.subscriber.ecommerce_customer:
        class: "%odiseo.mailchimp_plugin.subscriber.ecommerce_customer.class%"
        arguments:  ["@odiseo.mailchimp_plugin.mailchimp", "@sylius.context.channel"]
        tags:
            - { name: doctrine.event_subscriber }

    odiseo.mailchimp_plugin.subscriber.ecommerce_product:
        class: "%odiseo.mailchimp_plugin.subscriber.ecommerce_product.class%"
        arguments:  ["@odiseo.mailchimp_plugin.mailchimp"]
        tags:
            - { name: doctrine.event_subscriber }
