imports:
    - { resource: 'services/commands.yaml' }
    - { resource: 'services/handlers.yaml' }

services:
    # Providers
    odiseo_sylius_mailchimp_plugin.default.list_id_provider:
        class: Odiseo\SyliusMailchimpPlugin\Provider\DefaultListIdProvider
        arguments:
            - "%env(ODISEO_MAILCHIMP_DEFAULT_LISTID)%"

    # Api
    odiseo_sylius_mailchimp_plugin.ecommerce.api:
        class: Odiseo\SyliusMailchimpPlugin\Api\Ecommerce
        public: true
        arguments:
            - "%env(ODISEO_MAILCHIMP_APIKEY)%"

    odiseo_sylius_mailchimp_plugin.lists.api:
        class: Odiseo\SyliusMailchimpPlugin\Api\Lists
        public: true
        arguments:
            - "%env(ODISEO_MAILCHIMP_APIKEY)%"

    # Controllers
    odiseo_sylius_mailchimp_plugin.controller.action.subscribe_to_newsletter:
        class: Odiseo\SyliusMailchimpPlugin\Controller\Action\SubscribeToNewsletterAction
        public: true
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.handler.customer_newsletter_subscription"
            - "@translator"

    # Listeners
    odiseo_sylius_mailchimp_plugin.subscriber.store_subscriber:
        class: Odiseo\SyliusMailchimpPlugin\EventListener\StoreSubscriber
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.handler.store_register"
        tags:
            - { name: doctrine.event_subscriber }

    odiseo_sylius_mailchimp_plugin.subscriber.product_subscriber:
        class: Odiseo\SyliusMailchimpPlugin\EventListener\ProductSubscriber
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.handler.product_register"
        tags:
            - { name: doctrine.event_subscriber }

    odiseo_sylius_mailchimp_plugin.listener.customer_listener:
        class: Odiseo\SyliusMailchimpPlugin\EventListener\CustomerListener
        arguments:
            - "@odiseo_sylius_mailchimp_plugin.handler.customer_register"
            - "@odiseo_sylius_mailchimp_plugin.handler.customer_newsletter_subscription"
        tags:
            - { name: "kernel.event_listener", event: "sylius.customer.post_register", method: customerCreate }
            - { name: "kernel.event_listener", event: "sylius.customer.pre_update", method: customerUpdate }
