winzou_state_machine:
    sylius_order_checkout:
        callbacks:
            after:
                mailchimp_register_cart:
                    on: ["address"]
                    do: ["@odiseo.mailchimp_plugin.listener.ecommerce_cart", "registerCart"]
                    args: ["object"]
                    priority: 3
                mailchimp_register_order:
                    on: ["complete"]
                    do: ["@odiseo.mailchimp_plugin.listener.ecommerce_order", "registerOrder"]
                    args: ["object"]
                    priority: 3